kubernetesClusterDomain: cluster.local

streamlitApp:
  replicas: ${STREAMLIT_APP_REPLICAS}
  image:
    repository: ${STREAMLIT_APP_IMAGE_REPOSITORY}
    tag: ${STREAMLIT_APP_IMAGE_TAG}
  resources:
    limits:
      cpu: ${STREAMLIT_APP_CPU_LIMIT}
      memory: ${STREAMLIT_APP_MEMORY_LIMIT}
    requests:
      cpu: ${STREAMLIT_APP_CPU_REQUEST}
      memory: ${STREAMLIT_APP_MEMORY_REQUEST}

streamlitAppService:
  ports:
    - port: ${STREAMLIT_APP_SERVICE_PORT}
      targetPort: ${STREAMLIT_APP_SERVICE_TARGET_PORT}
  type: ${STREAMLIT_APP_SERVICE_TYPE}

secrets:
  CVE_DIRECTORY: ${CVE_DIRECTORY}
  GITHUB_API_URL: ${GITHUB_API_URL}
  PINECONE_API_KEY: ${PINECONE_API_KEY}
  myregistrykey:
    dockerconfigjson: ${MYREGISTRYKEY_DOCKERCONFIGJSON}
