---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  CVE_DIRECTORY: {{ .Values.secrets.kafkaPassword | b64enc | quote }}
  GITHUB_API_URL: {{ .Values.secrets.ZIP_URL | b64enc | quote }}
  PINECONE_API_KEY: {{ .Values.secrets.ZIP_URL | b64enc | quote }}